window.esdocSearchIndex = [
  [
    "./app/translation/altermenu.js~altermenu",
    "class/app/translation/AlterMenu.js~AlterMenu.html",
    "<span>AlterMenu</span> <span class=\"search-result-import-path\">./app/translation/AlterMenu.js</span>",
    "class"
  ],
  [
    "./app/subscription/articlelist.js~articlelist",
    "class/app/subscription/ArticleList.js~ArticleList.html",
    "<span>ArticleList</span> <span class=\"search-result-import-path\">./app/subscription/ArticleList.js</span>",
    "class"
  ],
  [
    "./app/cache.js~cache",
    "class/app/Cache.js~Cache.html",
    "<span>Cache</span> <span class=\"search-result-import-path\">./app/Cache.js</span>",
    "class"
  ],
  [
    "./app/subscription/feedsubscriber.js~feedsubscriber",
    "class/app/subscription/FeedSubscriber.js~FeedSubscriber.html",
    "<span>FeedSubscriber</span> <span class=\"search-result-import-path\">./app/subscription/FeedSubscriber.js</span>",
    "class"
  ],
  [
    "./app/subscription/languagemenu.js~languagemenu",
    "class/app/subscription/LanguageMenu.js~LanguageMenu.html",
    "<span>LanguageMenu</span> <span class=\"search-result-import-path\">./app/subscription/LanguageMenu.js</span>",
    "class"
  ],
  [
    "./app/subscription/nofeedtour.js~nofeedtour",
    "class/app/subscription/NoFeedTour.js~NoFeedTour.html",
    "<span>NoFeedTour</span> <span class=\"search-result-import-path\">./app/subscription/NoFeedTour.js</span>",
    "class"
  ],
  [
    "./app/notifier.js~notifier",
    "class/app/Notifier.js~Notifier.html",
    "<span>Notifier</span> <span class=\"search-result-import-path\">./app/Notifier.js</span>",
    "class"
  ],
  [
    "./app/translation/speaker.js~speaker",
    "class/app/translation/Speaker.js~Speaker.html",
    "<span>Speaker</span> <span class=\"search-result-import-path\">./app/translation/Speaker.js</span>",
    "class"
  ],
  [
    "./app/starer.js~starer",
    "class/app/Starer.js~Starer.html",
    "<span>Starer</span> <span class=\"search-result-import-path\">./app/Starer.js</span>",
    "class"
  ],
  [
    "./app/subscription/starredarticlelist.js~starredarticlelist",
    "class/app/subscription/StarredArticleList.js~StarredArticleList.html",
    "<span>StarredArticleList</span> <span class=\"search-result-import-path\">./app/subscription/StarredArticleList.js</span>",
    "class"
  ],
  [
    "./app/subscription/subscriptionlist.js~subscriptionlist",
    "class/app/subscription/SubscriptionList.js~SubscriptionList.html",
    "<span>SubscriptionList</span> <span class=\"search-result-import-path\">./app/subscription/SubscriptionList.js</span>",
    "class"
  ],
  [
    "./app/translation/translator.js~translator",
    "class/app/translation/Translator.js~Translator.html",
    "<span>Translator</span> <span class=\"search-result-import-path\">./app/translation/Translator.js</span>",
    "class"
  ],
  [
    "./app/translation/undostack.js~undostack",
    "class/app/translation/UndoStack.js~UndoStack.html",
    "<span>UndoStack</span> <span class=\"search-result-import-path\">./app/translation/UndoStack.js</span>",
    "class"
  ],
  [
    "./app/useractivitylogger.js~useractivitylogger",
    "class/app/UserActivityLogger.js~UserActivityLogger.html",
    "<span>UserActivityLogger</span> <span class=\"search-result-import-path\">./app/UserActivityLogger.js</span>",
    "class"
  ],
  [
    "./app/zeeguurequests.js~zeeguurequests",
    "class/app/zeeguuRequests.js~ZeeguuRequests.html",
    "<span>ZeeguuRequests</span> <span class=\"search-result-import-path\">./app/zeeguuRequests.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "app/cache.js",
    "file/app/Cache.js.html",
    "app/Cache.js",
    "file"
  ],
  [
    "app/cache.js~cache.has",
    "class/app/Cache.js~Cache.html#static-method-has",
    "app/Cache.js~Cache.has",
    "method"
  ],
  [
    "app/cache.js~cache.isavailable",
    "class/app/Cache.js~Cache.html#static-method-isAvailable",
    "app/Cache.js~Cache.isAvailable",
    "method"
  ],
  [
    "app/cache.js~cache.remove",
    "class/app/Cache.js~Cache.html#static-method-remove",
    "app/Cache.js~Cache.remove",
    "method"
  ],
  [
    "app/cache.js~cache.retrieve",
    "class/app/Cache.js~Cache.html#static-method-retrieve",
    "app/Cache.js~Cache.retrieve",
    "method"
  ],
  [
    "app/cache.js~cache.store",
    "class/app/Cache.js~Cache.html#static-method-store",
    "app/Cache.js~Cache.store",
    "method"
  ],
  [
    "app/notifier.js",
    "file/app/Notifier.js.html",
    "app/Notifier.js",
    "file"
  ],
  [
    "app/notifier.js~notifier#constructor",
    "class/app/Notifier.js~Notifier.html#instance-constructor-constructor",
    "app/Notifier.js~Notifier#constructor",
    "method"
  ],
  [
    "app/notifier.js~notifier#lastmessage",
    "class/app/Notifier.js~Notifier.html#instance-member-lastMessage",
    "app/Notifier.js~Notifier#lastMessage",
    "member"
  ],
  [
    "app/notifier.js~notifier#notify",
    "class/app/Notifier.js~Notifier.html#instance-method-notify",
    "app/Notifier.js~Notifier#notify",
    "method"
  ],
  [
    "app/starer.js",
    "file/app/Starer.js.html",
    "app/Starer.js",
    "file"
  ],
  [
    "app/starer.js~starer#_toggleicon",
    "class/app/Starer.js~Starer.html#instance-method-_toggleIcon",
    "app/Starer.js~Starer#_toggleIcon",
    "method"
  ],
  [
    "app/starer.js~starer#_togglestate",
    "class/app/Starer.js~Starer.html#instance-method-_toggleState",
    "app/Starer.js~Starer#_toggleState",
    "method"
  ],
  [
    "app/starer.js~starer#constructor",
    "class/app/Starer.js~Starer.html#instance-constructor-constructor",
    "app/Starer.js~Starer#constructor",
    "method"
  ],
  [
    "app/starer.js~starer#on",
    "class/app/Starer.js~Starer.html#instance-member-on",
    "app/Starer.js~Starer#on",
    "member"
  ],
  [
    "app/starer.js~starer#setstate",
    "class/app/Starer.js~Starer.html#instance-method-setState",
    "app/Starer.js~Starer#setState",
    "method"
  ],
  [
    "app/starer.js~starer#toggle",
    "class/app/Starer.js~Starer.html#instance-method-toggle",
    "app/Starer.js~Starer#toggle",
    "method"
  ],
  [
    "app/useractivitylogger.js",
    "file/app/UserActivityLogger.js.html",
    "app/UserActivityLogger.js",
    "file"
  ],
  [
    "app/useractivitylogger.js~useractivitylogger._onreply",
    "class/app/UserActivityLogger.js~UserActivityLogger.html#static-method-_onReply",
    "app/UserActivityLogger.js~UserActivityLogger._onReply",
    "method"
  ],
  [
    "app/useractivitylogger.js~useractivitylogger.log",
    "class/app/UserActivityLogger.js~UserActivityLogger.html#static-method-log",
    "app/UserActivityLogger.js~UserActivityLogger.log",
    "method"
  ],
  [
    "app/config.js",
    "file/app/config.js.html",
    "app/config.js",
    "file"
  ],
  [
    "app/subscription/articlelist.js",
    "file/app/subscription/ArticleList.js.html",
    "app/subscription/ArticleList.js",
    "file"
  ],
  [
    "app/subscription/articlelist.js~articlelist#_loadarticlelinks",
    "class/app/subscription/ArticleList.js~ArticleList.html#instance-method-_loadArticleLinks",
    "app/subscription/ArticleList.js~ArticleList#_loadArticleLinks",
    "method"
  ],
  [
    "app/subscription/articlelist.js~articlelist#_renderarticlelinks",
    "class/app/subscription/ArticleList.js~ArticleList.html#instance-method-_renderArticleLinks",
    "app/subscription/ArticleList.js~ArticleList#_renderArticleLinks",
    "method"
  ],
  [
    "app/subscription/articlelist.js~articlelist#clear",
    "class/app/subscription/ArticleList.js~ArticleList.html#instance-method-clear",
    "app/subscription/ArticleList.js~ArticleList#clear",
    "method"
  ],
  [
    "app/subscription/articlelist.js~articlelist#constructor",
    "class/app/subscription/ArticleList.js~ArticleList.html#instance-constructor-constructor",
    "app/subscription/ArticleList.js~ArticleList#constructor",
    "method"
  ],
  [
    "app/subscription/articlelist.js~articlelist#load",
    "class/app/subscription/ArticleList.js~ArticleList.html#instance-method-load",
    "app/subscription/ArticleList.js~ArticleList#load",
    "method"
  ],
  [
    "app/subscription/articlelist.js~articlelist#nofeedtour",
    "class/app/subscription/ArticleList.js~ArticleList.html#instance-member-noFeedTour",
    "app/subscription/ArticleList.js~ArticleList#noFeedTour",
    "member"
  ],
  [
    "app/subscription/articlelist.js~articlelist#remove",
    "class/app/subscription/ArticleList.js~ArticleList.html#instance-method-remove",
    "app/subscription/ArticleList.js~ArticleList#remove",
    "method"
  ],
  [
    "app/subscription/feedsubscriber.js",
    "file/app/subscription/FeedSubscriber.js.html",
    "app/subscription/FeedSubscriber.js",
    "file"
  ],
  [
    "app/subscription/feedsubscriber.js~feedsubscriber#_loadfeedoptions",
    "class/app/subscription/FeedSubscriber.js~FeedSubscriber.html#instance-method-_loadFeedOptions",
    "app/subscription/FeedSubscriber.js~FeedSubscriber#_loadFeedOptions",
    "method"
  ],
  [
    "app/subscription/feedsubscriber.js~feedsubscriber#_setcurrentlanguage",
    "class/app/subscription/FeedSubscriber.js~FeedSubscriber.html#instance-method-_setCurrentLanguage",
    "app/subscription/FeedSubscriber.js~FeedSubscriber#_setCurrentLanguage",
    "method"
  ],
  [
    "app/subscription/feedsubscriber.js~feedsubscriber#clear",
    "class/app/subscription/FeedSubscriber.js~FeedSubscriber.html#instance-method-clear",
    "app/subscription/FeedSubscriber.js~FeedSubscriber#clear",
    "method"
  ],
  [
    "app/subscription/feedsubscriber.js~feedsubscriber#constructor",
    "class/app/subscription/FeedSubscriber.js~FeedSubscriber.html#instance-constructor-constructor",
    "app/subscription/FeedSubscriber.js~FeedSubscriber#constructor",
    "method"
  ],
  [
    "app/subscription/feedsubscriber.js~feedsubscriber#currentlanguage",
    "class/app/subscription/FeedSubscriber.js~FeedSubscriber.html#instance-member-currentLanguage",
    "app/subscription/FeedSubscriber.js~FeedSubscriber#currentLanguage",
    "member"
  ],
  [
    "app/subscription/feedsubscriber.js~feedsubscriber#getcurrentlanguage",
    "class/app/subscription/FeedSubscriber.js~FeedSubscriber.html#instance-method-getCurrentLanguage",
    "app/subscription/FeedSubscriber.js~FeedSubscriber#getCurrentLanguage",
    "method"
  ],
  [
    "app/subscription/feedsubscriber.js~feedsubscriber#languagemenu",
    "class/app/subscription/FeedSubscriber.js~FeedSubscriber.html#instance-member-languageMenu",
    "app/subscription/FeedSubscriber.js~FeedSubscriber#languageMenu",
    "member"
  ],
  [
    "app/subscription/feedsubscriber.js~feedsubscriber#load",
    "class/app/subscription/FeedSubscriber.js~FeedSubscriber.html#instance-method-load",
    "app/subscription/FeedSubscriber.js~FeedSubscriber#load",
    "method"
  ],
  [
    "app/subscription/feedsubscriber.js~feedsubscriber#open",
    "class/app/subscription/FeedSubscriber.js~FeedSubscriber.html#instance-method-open",
    "app/subscription/FeedSubscriber.js~FeedSubscriber#open",
    "method"
  ],
  [
    "app/subscription/feedsubscriber.js~feedsubscriber#subscriptionlist",
    "class/app/subscription/FeedSubscriber.js~FeedSubscriber.html#instance-member-subscriptionList",
    "app/subscription/FeedSubscriber.js~FeedSubscriber#subscriptionList",
    "member"
  ],
  [
    "app/subscription/languagemenu.js",
    "file/app/subscription/LanguageMenu.js.html",
    "app/subscription/LanguageMenu.js",
    "file"
  ],
  [
    "app/subscription/languagemenu.js~languagemenu#_loadlanguageoptions",
    "class/app/subscription/LanguageMenu.js~LanguageMenu.html#instance-method-_loadLanguageOptions",
    "app/subscription/LanguageMenu.js~LanguageMenu#_loadLanguageOptions",
    "method"
  ],
  [
    "app/subscription/languagemenu.js~languagemenu#load",
    "class/app/subscription/LanguageMenu.js~LanguageMenu.html#instance-method-load",
    "app/subscription/LanguageMenu.js~LanguageMenu#load",
    "method"
  ],
  [
    "app/subscription/nofeedtour.js",
    "file/app/subscription/NoFeedTour.js.html",
    "app/subscription/NoFeedTour.js",
    "file"
  ],
  [
    "app/subscription/nofeedtour.js~nofeedtour#hide",
    "class/app/subscription/NoFeedTour.js~NoFeedTour.html#instance-method-hide",
    "app/subscription/NoFeedTour.js~NoFeedTour#hide",
    "method"
  ],
  [
    "app/subscription/nofeedtour.js~nofeedtour#show",
    "class/app/subscription/NoFeedTour.js~NoFeedTour.html#instance-method-show",
    "app/subscription/NoFeedTour.js~NoFeedTour#show",
    "method"
  ],
  [
    "app/subscription/starredarticlelist.js",
    "file/app/subscription/StarredArticleList.js.html",
    "app/subscription/StarredArticleList.js",
    "file"
  ],
  [
    "app/subscription/starredarticlelist.js~starredarticlelist#_renderarticlelinks",
    "class/app/subscription/StarredArticleList.js~StarredArticleList.html#instance-method-_renderArticleLinks",
    "app/subscription/StarredArticleList.js~StarredArticleList#_renderArticleLinks",
    "method"
  ],
  [
    "app/subscription/starredarticlelist.js~starredarticlelist#load",
    "class/app/subscription/StarredArticleList.js~StarredArticleList.html#instance-method-load",
    "app/subscription/StarredArticleList.js~StarredArticleList#load",
    "method"
  ],
  [
    "app/subscription/subscriptionlist.js",
    "file/app/subscription/SubscriptionList.js.html",
    "app/subscription/SubscriptionList.js",
    "file"
  ],
  [
    "app/subscription/subscriptionlist.js~subscriptionlist#_addsubscription",
    "class/app/subscription/SubscriptionList.js~SubscriptionList.html#instance-method-_addSubscription",
    "app/subscription/SubscriptionList.js~SubscriptionList#_addSubscription",
    "method"
  ],
  [
    "app/subscription/subscriptionlist.js~subscriptionlist#_changed",
    "class/app/subscription/SubscriptionList.js~SubscriptionList.html#instance-method-_changed",
    "app/subscription/SubscriptionList.js~SubscriptionList#_changed",
    "method"
  ],
  [
    "app/subscription/subscriptionlist.js~subscriptionlist#_loadsubscriptions",
    "class/app/subscription/SubscriptionList.js~SubscriptionList.html#instance-method-_loadSubscriptions",
    "app/subscription/SubscriptionList.js~SubscriptionList#_loadSubscriptions",
    "method"
  ],
  [
    "app/subscription/subscriptionlist.js~subscriptionlist#_onfeedfollowed",
    "class/app/subscription/SubscriptionList.js~SubscriptionList.html#instance-method-_onFeedFollowed",
    "app/subscription/SubscriptionList.js~SubscriptionList#_onFeedFollowed",
    "method"
  ],
  [
    "app/subscription/subscriptionlist.js~subscriptionlist#_onfeedunfollowed",
    "class/app/subscription/SubscriptionList.js~SubscriptionList.html#instance-method-_onFeedUnfollowed",
    "app/subscription/SubscriptionList.js~SubscriptionList#_onFeedUnfollowed",
    "method"
  ],
  [
    "app/subscription/subscriptionlist.js~subscriptionlist#_remove",
    "class/app/subscription/SubscriptionList.js~SubscriptionList.html#instance-method-_remove",
    "app/subscription/SubscriptionList.js~SubscriptionList#_remove",
    "method"
  ],
  [
    "app/subscription/subscriptionlist.js~subscriptionlist#_unfollow",
    "class/app/subscription/SubscriptionList.js~SubscriptionList.html#instance-method-_unfollow",
    "app/subscription/SubscriptionList.js~SubscriptionList#_unfollow",
    "method"
  ],
  [
    "app/subscription/subscriptionlist.js~subscriptionlist#clear",
    "class/app/subscription/SubscriptionList.js~SubscriptionList.html#instance-method-clear",
    "app/subscription/SubscriptionList.js~SubscriptionList#clear",
    "method"
  ],
  [
    "app/subscription/subscriptionlist.js~subscriptionlist#constructor",
    "class/app/subscription/SubscriptionList.js~SubscriptionList.html#instance-constructor-constructor",
    "app/subscription/SubscriptionList.js~SubscriptionList#constructor",
    "method"
  ],
  [
    "app/subscription/subscriptionlist.js~subscriptionlist#feedlist",
    "class/app/subscription/SubscriptionList.js~SubscriptionList.html#instance-member-feedList",
    "app/subscription/SubscriptionList.js~SubscriptionList#feedList",
    "member"
  ],
  [
    "app/subscription/subscriptionlist.js~subscriptionlist#follow",
    "class/app/subscription/SubscriptionList.js~SubscriptionList.html#instance-method-follow",
    "app/subscription/SubscriptionList.js~SubscriptionList#follow",
    "method"
  ],
  [
    "app/subscription/subscriptionlist.js~subscriptionlist#load",
    "class/app/subscription/SubscriptionList.js~SubscriptionList.html#instance-method-load",
    "app/subscription/SubscriptionList.js~SubscriptionList#load",
    "method"
  ],
  [
    "app/subscription/subscriptionlist.js~subscriptionlist#notifier",
    "class/app/subscription/SubscriptionList.js~SubscriptionList.html#instance-member-notifier",
    "app/subscription/SubscriptionList.js~SubscriptionList#notifier",
    "member"
  ],
  [
    "app/subscription/subscriptionlist.js~subscriptionlist#refresh",
    "class/app/subscription/SubscriptionList.js~SubscriptionList.html#instance-method-refresh",
    "app/subscription/SubscriptionList.js~SubscriptionList#refresh",
    "method"
  ],
  [
    "app/subscription/main.js",
    "file/app/subscription/main.js.html",
    "app/subscription/main.js",
    "file"
  ],
  [
    "app/translation/altermenu.js",
    "file/app/translation/AlterMenu.js.html",
    "app/translation/AlterMenu.js",
    "file"
  ],
  [
    "app/translation/altermenu.js~altermenu#_appendinputfield",
    "class/app/translation/AlterMenu.js~AlterMenu.html#instance-method-_appendInputField",
    "app/translation/AlterMenu.js~AlterMenu#_appendInputField",
    "method"
  ],
  [
    "app/translation/altermenu.js~altermenu#_place",
    "class/app/translation/AlterMenu.js~AlterMenu.html#instance-method-_place",
    "app/translation/AlterMenu.js~AlterMenu#_place",
    "method"
  ],
  [
    "app/translation/altermenu.js~altermenu#_sendswappedtranslation",
    "class/app/translation/AlterMenu.js~AlterMenu.html#instance-method-_sendSwappedTranslation",
    "app/translation/AlterMenu.js~AlterMenu#_sendSwappedTranslation",
    "method"
  ],
  [
    "app/translation/altermenu.js~altermenu#_swapprimarytranslation",
    "class/app/translation/AlterMenu.js~AlterMenu.html#instance-method-_swapPrimaryTranslation",
    "app/translation/AlterMenu.js~AlterMenu#_swapPrimaryTranslation",
    "method"
  ],
  [
    "app/translation/altermenu.js~altermenu#build",
    "class/app/translation/AlterMenu.js~AlterMenu.html#instance-method-build",
    "app/translation/AlterMenu.js~AlterMenu#build",
    "method"
  ],
  [
    "app/translation/altermenu.js~altermenu#close",
    "class/app/translation/AlterMenu.js~AlterMenu.html#instance-method-close",
    "app/translation/AlterMenu.js~AlterMenu#close",
    "method"
  ],
  [
    "app/translation/altermenu.js~altermenu#construct",
    "class/app/translation/AlterMenu.js~AlterMenu.html#instance-method-construct",
    "app/translation/AlterMenu.js~AlterMenu#construct",
    "method"
  ],
  [
    "app/translation/altermenu.js~altermenu#constructor",
    "class/app/translation/AlterMenu.js~AlterMenu.html#instance-constructor-constructor",
    "app/translation/AlterMenu.js~AlterMenu#constructor",
    "method"
  ],
  [
    "app/translation/altermenu.js~altermenu#isopen",
    "class/app/translation/AlterMenu.js~AlterMenu.html#instance-method-isOpen",
    "app/translation/AlterMenu.js~AlterMenu#isOpen",
    "method"
  ],
  [
    "app/translation/altermenu.js~altermenu#menuopen",
    "class/app/translation/AlterMenu.js~AlterMenu.html#instance-member-menuOpen",
    "app/translation/AlterMenu.js~AlterMenu#menuOpen",
    "member"
  ],
  [
    "app/translation/altermenu.js~altermenu#notifier",
    "class/app/translation/AlterMenu.js~AlterMenu.html#instance-member-notifier",
    "app/translation/AlterMenu.js~AlterMenu#notifier",
    "member"
  ],
  [
    "app/translation/altermenu.js~altermenu#open",
    "class/app/translation/AlterMenu.js~AlterMenu.html#instance-method-open",
    "app/translation/AlterMenu.js~AlterMenu#open",
    "method"
  ],
  [
    "app/translation/altermenu.js~altermenu#reposition",
    "class/app/translation/AlterMenu.js~AlterMenu.html#instance-method-reposition",
    "app/translation/AlterMenu.js~AlterMenu#reposition",
    "method"
  ],
  [
    "app/translation/speaker.js",
    "file/app/translation/Speaker.js.html",
    "app/translation/Speaker.js",
    "file"
  ],
  [
    "app/translation/speaker.js~speaker#speak",
    "class/app/translation/Speaker.js~Speaker.html#instance-method-speak",
    "app/translation/Speaker.js~Speaker#speak",
    "method"
  ],
  [
    "app/translation/translator.js",
    "file/app/translation/Translator.js.html",
    "app/translation/Translator.js",
    "file"
  ],
  [
    "app/translation/translator.js~translator#_buildconnectivesset",
    "class/app/translation/Translator.js~Translator.html#instance-method-_buildConnectivesSet",
    "app/translation/Translator.js~Translator#_buildConnectivesSet",
    "method"
  ],
  [
    "app/translation/translator.js~translator#_mergezeeguu",
    "class/app/translation/Translator.js~Translator.html#instance-method-_mergeZeeguu",
    "app/translation/Translator.js~Translator#_mergeZeeguu",
    "method"
  ],
  [
    "app/translation/translator.js~translator#_settranslations",
    "class/app/translation/Translator.js~Translator.html#instance-method-_setTranslations",
    "app/translation/Translator.js~Translator#_setTranslations",
    "method"
  ],
  [
    "app/translation/translator.js~translator#connectivesset",
    "class/app/translation/Translator.js~Translator.html#instance-member-connectivesSet",
    "app/translation/Translator.js~Translator#connectivesSet",
    "member"
  ],
  [
    "app/translation/translator.js~translator#constructor",
    "class/app/translation/Translator.js~Translator.html#instance-constructor-constructor",
    "app/translation/Translator.js~Translator#constructor",
    "method"
  ],
  [
    "app/translation/translator.js~translator#istranslated",
    "class/app/translation/Translator.js~Translator.html#instance-method-isTranslated",
    "app/translation/Translator.js~Translator#isTranslated",
    "method"
  ],
  [
    "app/translation/translator.js~translator#sendsuggestion",
    "class/app/translation/Translator.js~Translator.html#instance-method-sendSuggestion",
    "app/translation/Translator.js~Translator#sendSuggestion",
    "method"
  ],
  [
    "app/translation/translator.js~translator#translate",
    "class/app/translation/Translator.js~Translator.html#instance-method-translate",
    "app/translation/Translator.js~Translator#translate",
    "method"
  ],
  [
    "app/translation/translator.js~translator#undostack",
    "class/app/translation/Translator.js~Translator.html#instance-member-undoStack",
    "app/translation/Translator.js~Translator#undoStack",
    "member"
  ],
  [
    "app/translation/translator.js~translator#undotranslate",
    "class/app/translation/Translator.js~Translator.html#instance-method-undoTranslate",
    "app/translation/Translator.js~Translator#undoTranslate",
    "method"
  ],
  [
    "app/translation/translator.js~translator._getcontext",
    "class/app/translation/Translator.js~Translator.html#static-method-_getContext",
    "app/translation/Translator.js~Translator._getContext",
    "method"
  ],
  [
    "app/translation/undostack.js",
    "file/app/translation/UndoStack.js.html",
    "app/translation/UndoStack.js",
    "file"
  ],
  [
    "app/translation/undostack.js~undostack#constructor",
    "class/app/translation/UndoStack.js~UndoStack.html#instance-constructor-constructor",
    "app/translation/UndoStack.js~UndoStack#constructor",
    "method"
  ],
  [
    "app/translation/undostack.js~undostack#pushstate",
    "class/app/translation/UndoStack.js~UndoStack.html#instance-method-pushState",
    "app/translation/UndoStack.js~UndoStack#pushState",
    "method"
  ],
  [
    "app/translation/undostack.js~undostack#stack",
    "class/app/translation/UndoStack.js~UndoStack.html#instance-member-stack",
    "app/translation/UndoStack.js~UndoStack#stack",
    "member"
  ],
  [
    "app/translation/undostack.js~undostack#undostate",
    "class/app/translation/UndoStack.js~UndoStack.html#instance-method-undoState",
    "app/translation/UndoStack.js~UndoStack#undoState",
    "method"
  ],
  [
    "app/translation/main.js",
    "file/app/translation/main.js.html",
    "app/translation/main.js",
    "file"
  ],
  [
    "app/zeeguurequests.js",
    "file/app/zeeguuRequests.js.html",
    "app/zeeguuRequests.js",
    "file"
  ],
  [
    "app/zeeguurequests.js~zeeguurequests._readcookie",
    "class/app/zeeguuRequests.js~ZeeguuRequests.html#static-method-_readCookie",
    "app/zeeguuRequests.js~ZeeguuRequests._readCookie",
    "method"
  ],
  [
    "app/zeeguurequests.js~zeeguurequests.get",
    "class/app/zeeguuRequests.js~ZeeguuRequests.html#static-method-get",
    "app/zeeguuRequests.js~ZeeguuRequests.get",
    "method"
  ],
  [
    "app/zeeguurequests.js~zeeguurequests.post",
    "class/app/zeeguuRequests.js~ZeeguuRequests.html#static-method-post",
    "app/zeeguuRequests.js~ZeeguuRequests.post",
    "method"
  ],
  [
    "app/zeeguurequests.js~zeeguurequests.session",
    "class/app/zeeguuRequests.js~ZeeguuRequests.html#static-method-session",
    "app/zeeguuRequests.js~ZeeguuRequests.session",
    "method"
  ]
]